# Generated by Django 4.0.4 on 2022-05-31 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='task_name',
            new_name='task_ref',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_name',
            new_name='task_ref',
        ),
    ]
