# Generated by Django 4.0.4 on 2022-05-31 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_task_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtask_priority', to='tasks.priority'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskpriority', to='tasks.priority'),
        ),
    ]
